import React,{useEffect,useMemo,useState} from 'react';
import {Megaphone, Plus, Trash2, PlayCircle, ChevronRight, Radio} from 'lucide-react';
import {getSponsors,upsertSponsor,deleteSponsor,getActiveSponsors,getAnnouncements,enqueueAnnouncement,removeAnnouncement,getAnnouncementQueue,dequeueAnnouncement,subscribeBroadcastOps,type BroadcastSponsor,type BroadcastAnnouncement,type SponsorSlot} from '@/lib/broadcast-ops';
import {useI18n} from '@/lib/i18n';

const slots:SponsorSlot[]=['break','match-intro','result','mvp','ranking','awards'];
export default function BroadcastOperationsPanel(){
 const {lang}=useI18n(); const ar=lang==='ar'; const fr=lang==='fr';
 const [sponsors,setSponsors]=useState(getSponsors()); const [anns,setAnns]=useState(getAnnouncements()); const [queue,setQueue]=useState(getAnnouncementQueue());
 const [sponsorName,setSponsorName]=useState(''); const [announcement,setAnnouncement]=useState('');
 const refresh=()=>{setSponsors(getSponsors());setAnns(getAnnouncements());setQueue(getAnnouncementQueue())};
 useEffect(()=>subscribeBroadcastOps(refresh),[]);
 const current=useMemo(()=>getActiveSponsors('break')[0], [sponsors]);
 const addSponsor=()=>{if(!sponsorName.trim())return;upsertSponsor({id:`sponsor-${Date.now()}`,name:sponsorName.trim(),priority:10,duration:10,slots:['break','match-intro','result'],active:true});setSponsorName('');refresh()};
 const addAnnouncement=()=>{if(!announcement.trim())return;enqueueAnnouncement({id:`ann-${Date.now()}`,title:ar?'إعلان بث':fr?'Annonce diffusion':'Broadcast announcement',message:announcement.trim(),duration:8,priority:10,severity:'info',slots:['break','match-start','custom'],active:true,createdAt:new Date().toISOString()});setAnnouncement('');refresh()};
 return <section className="panel p-4 border border-yellow-400/10 space-y-4">
   <div className="flex items-center justify-between"><div><div className="font-display font-black text-sm text-yellow-200 flex items-center gap-2"><Radio size={15}/> {ar?'عمليات البث':'Broadcast Operations'}</div><div className="text-[9px] text-white/40 mt-1">{ar?'إعلانات ورعاة ودوران آمن أثناء الفواصل — بدون لمس بيانات المباراة.':fr?'Annonces et sponsors, sans toucher aux données officielles.':'Announcements and sponsor rotation without modifying official match data.'}</div></div><span className="text-[8px] text-emerald-300">READ-ONLY DATA</span></div>
   <div className="grid lg:grid-cols-2 gap-4">
    <div className="rounded-xl border border-white/10 p-3 space-y-2"><div className="text-[9px] font-black tracking-widest text-white/60 flex items-center gap-2"><Megaphone size={12}/> SPONSORS</div><div className="flex gap-2"><input value={sponsorName} onChange={e=>setSponsorName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addSponsor()} placeholder={ar?'اسم الراعي':'Sponsor name'} className="flex-1 rounded-lg bg-black/30 border border-white/10 px-2 py-2 text-xs"/><button onClick={addSponsor} className="px-3 rounded-lg bg-yellow-400/15 border border-yellow-400/25 text-yellow-200"><Plus size={14}/></button></div>{sponsors.slice(0,6).map(s=><div key={s.id} className="flex items-center justify-between rounded-lg bg-white/[.025] px-2 py-2"><div><div className="text-xs font-bold">{s.name}</div><div className="text-[8px] text-white/35">{s.duration}s · {s.slots.join(' · ')}</div></div><button onClick={()=>{deleteSponsor(s.id);refresh()}} className="text-red-300/60 hover:text-red-300"><Trash2 size={12}/></button></div>)}{current&&<div className="text-[8px] text-emerald-300/70">NEXT BREAK SPONSOR: {current.name}</div>}</div>
    <div className="rounded-xl border border-white/10 p-3 space-y-2"><div className="text-[9px] font-black tracking-widest text-white/60 flex items-center gap-2"><Megaphone size={12}/> ANNOUNCEMENT QUEUE</div><div className="flex gap-2"><input value={announcement} onChange={e=>setAnnouncement(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addAnnouncement()} placeholder={ar?'اكتب إعلانًا…':'Write announcement…'} className="flex-1 rounded-lg bg-black/30 border border-white/10 px-2 py-2 text-xs"/><button onClick={addAnnouncement} className="px-3 rounded-lg bg-cyan-400/10 border border-cyan-400/20 text-cyan-200"><Plus size={14}/></button></div>{queue.map((a,i)=><div key={a.id} className="flex items-center justify-between rounded-lg bg-white/[.025] px-2 py-2"><div className="min-w-0"><div className="text-xs font-bold truncate">{a.message}</div><div className="text-[8px] text-white/35">#{i+1} · {a.duration}s · {a.severity.toUpperCase()}</div></div><button onClick={()=>{dequeueAnnouncement(a.id);refresh()}} className="text-cyan-300/70"><ChevronRight size={13}/></button></div>)}{!queue.length&&<div className="text-[9px] text-white/30">{ar?'لا توجد إعلانات في الطابور.':'Queue is empty.'}</div>}<div className="text-[8px] text-white/35">{anns.length} stored · {queue.length} queued</div></div>
   </div>
 </section>
}
