import React, { useEffect, useRef } from 'react';
import { AWARD_ANIMATION_KEY_MAP, default as AwardAnimationRenderer } from './AwardAnimationRenderer';
import type { BroadcastDesign } from '@/lib/broadcast-design';

export default function BroadcastDesignStudioAwardPreview({ animationId, design }: { animationId: string; design: BroadcastDesign }) {
  const rootRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{ const root=rootRef.current; if(!root)return; const timer=window.setTimeout(()=>{ const nodes=Array.from(root.querySelectorAll<HTMLElement>('[data-wab-layer-id]')).filter(n=>n.dataset.wabStudioUi!=='1'); const layers=nodes.map((n,i)=>{const r=n.getBoundingClientRect(),rr=root.getBoundingClientRect(),cs=getComputedStyle(n),text=n.children.length===0?(n.textContent||'').trim():undefined;return {id:n.dataset.wabLayerId||`award:${i}`,name:n.getAttribute('aria-label')||n.getAttribute('title')||text||n.dataset.wabLayerId||`AWARD ${i+1}`,type:n.tagName.toLowerCase()==='img'?'image':text?'text':'frame',visible:true,locked:false,parentId:null,x:(r.left-rr.left)/rr.width*1920,y:(r.top-rr.top)/rr.height*1080,width:r.width/rr.width*1920,height:r.height/rr.height*1080,rotation:0,scale:1,opacity:Number(cs.opacity||1),zIndex:Number(cs.zIndex)||i+1,color:cs.color,background:cs.backgroundColor,borderColor:cs.borderColor,borderWidth:parseFloat(cs.borderTopWidth)||0,borderRadius:parseFloat(cs.borderTopLeftRadius)||0,fontFamily:cs.fontFamily,fontSize:parseFloat(cs.fontSize)||undefined,fontWeight:cs.fontWeight,text,imageSrc:n.tagName.toLowerCase()==='img'?(n as HTMLImageElement).currentSrc||n.getAttribute('src')||'':undefined,keyframes:[],sourceKey:`award-native:${animationId}:${n.dataset.wabLayerId||i}`};}); window.dispatchEvent(new CustomEvent('wab-studio-preview-snapshot',{detail:{animationId,layers}})); },80); return()=>window.clearTimeout(timer); },[animationId,design.currentTime]);
  const key=AWARD_ANIMATION_KEY_MAP[animationId]||'best_player';
  const selectedIds=design.selectedLayerIds?.length?design.selectedLayerIds:(design.selectedLayerId?[design.selectedLayerId]:[]);
  return <div ref={rootRef} className="absolute inset-0" data-wab-layer-root="award"><AwardAnimationRenderer awardKey={key} design={design} selectedIds={selectedIds} studio controls playing={false} onSelect={(id,additive)=>window.dispatchEvent(new CustomEvent('wab-studio-select-layer',{detail:{id,additive}}))}/></div>;
}
